on: push
name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          # We need nightly for fmt
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - uses: Jimver/cuda-toolkit@0.2.8
        id: cuda-toolkit
        with:
          cuda: "11.7.0"
      - name: Lint (clippy)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
      - name: Lint (rustfmt)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, 1.57, nightly]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: Jimver/cuda-toolkit@0.2.8
        id: cuda-toolkit
        with:
          cuda: "11.7.0"
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
      - name: Build all targets with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - name: Doctests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with latest nextest release
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        if: startsWith(matrix.rust-version, 'stable')
        run: cargo llvm-cov nextest --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        if: startsWith(matrix.rust-version, 'stable')
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
